name:                game-of-life
version:             0.0.0.0
github:              "nahiluhmot/game-of-life"
license:             BSD3
author:              "Tom Hulihan"
maintainer:          "hulihan.tom159@gmail.com"
copyright:           "2019 Tom Hulihan"

extra-source-files:
- README.md

synopsis:            Terminal "Game of life" using vectors
category:            Fun
description:         Please see the README on GitHub at <https://github.com/nahilhumot/game-of-life>
dependencies:
- base >= 4.7 && < 5
- async >= 2.2 && < 3
- mtl >= 2.2 && < 3
- random >= 1.1 && < 2
- stm >= 2.5 && < 3
- vector >= 0.12 && < 1
- vty >= 5.25 && < 6

library:
  source-dirs: src

executables:
  game-of-life-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game-of-life
